apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-bsyo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-bsyo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-bsyo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-bsyo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-bsyo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bmbn-tenant/rhtap-demo-app/hacbs-test-project-bsyo@sha256:8f777f6ef4003bdd172a3f14fbe48984e876ba0661f506e0d1d769eec9c223d4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
